filters = [
	{ "filter": "book", "text": "Books" },
	{ "filter": "comic", "text": "Comics" },
	{ "filter": "vg", "text": "Gaming" },
	{ "filter": "history", "text": "History" },
	{ "filter": "movie", "text": "Movies" },
	{ "filter": "tv", "text": "Tv" },
	{ "filter": "web", "text": "Web" },
]

posters = [
	{ "file": "assassins-creed.jpg", "filters": "vg", "label": "Assassin's Creed Series", "link": "https://www.ubisoft.com/en-ca/game/assassins-creed" },
	{ "file": "autobiogaphy-malcolm-x.jpg", "filters": "book history", "label": "The Autobiogaphy of Malcolm X", "link": "http://www.randomhousebooks.com/books/106490/" },
	{ "file": "batman-arkham.jpg", "filters": "vg comic", "label": "Batman: Arkham Series", "link": "https://rocksteadyltd.com/" },
	{ "file": "boys.jpg", "filters": "tv comic", "label": "The Boys", "link": "https://www.primevideo.com/detail/The-Boys/0KRGHGZCHKS920ZQGY5LBRF7MA" },
	{ "file": "brooklyn-nine-nine.jpg", "filters": "tv", "label": "Brooklyn Nine-Nine", "link": "https://www.netflix.com/title/70281562" },
	{ "file": "community.jpg", "filters": "tv", "label": "Community", "link": "https://www.netflix.com/title/70155589" },
	{ "file": "dark-knight-trilogy.jpg", "filters": "comic movie", "label": "The Dark Knight Trilogy", "link": "https://www.netflix.com/title/70213514" },
	{ "file": "dc-arrowverse.jpg", "filters": "tv comic", "label": "DC's Arrowverse", "link": "https://en.wikipedia.org/wiki/Arrowverse" },
	{ "file": "dc-extended-universe.jpg", "filters": "comic movie", "label": "DC Extended Universe", "link": "" },
	{ "file": "dirilis-ertugrul.jpg", "filters": "tv history", "label": "Dirilis Ertugrul", "link": "https://en.wikipedia.org/wiki/Dirili%C5%9F:_Ertu%C4%9Frul" },
	{ "file": "dragon-ball.jpg", "filters": "tv", "label": "Dragon Ball Series", "link": "http://www.toei-animation-usa.com/dragon-ball.html" },
	{ "file": "inglorious-basterds.jpg", "filters": "movie history", "label": "Inglorious Basterds", "link": "https://www.netflix.com/title/70108777" },
	{ "file": "killer-instinct.jpg", "filters": "vg", "label": "Killer Instinct", "link": "https://www.ultra-combo.com/" },
	{ "file": "kims-convenience.jpg", "filters": "tv", "label": "Kim's Convenience", "link": "https://www.netflix.com/title/80199128" },
	{ "file": "last-kingdom.jpg", "filters": "tv history", "label": "The Last Kingdom", "link": "https://www.netflix.com/title/80074249" },
	{ "file": "locke-and-key.jpg", "filters": "tv", "label": "Locke & Key", "link": "https://www.netflix.com/title/80241239" },
	{ "file": "lord-of-the-rings.jpg", "filters": "movie", "label": "Lord of the Rings Series", "link": "https://www.netflix.com/title/60004480" },
	{ "file": "mandalorian.jpg", "filters": "tv", "label": "The Mandalorian", "link": "https://disneyplusoriginals.disney.com/show/the-mandalorian" },
	{ "file": "marvel-cinematic-universe.jpg", "filters": "movie comic", "label": "Marvel Cinematic Universe", "link": "https://www.marvel.com/movies" },
	{ "file": "mmpr-boom-studios.jpg", "filters": "comic", "label": "MMPR Boom! Studios Series", "link": "https://www.boom-studios.com/series/mighty-morphin-power-rangers/" },
	{ "file": "nineteen-eighty-four.jpg", "filters": "book", "label": "Nineteen Eighty-Four", "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four" },
	{ "file": "patriot-act-with-hasan-minhaj.jpg", "filters": "tv", "label": "Patriot Act with Hasan Minhaj", "link": "https://www.netflix.com/title/80239931" },
	{ "file": "power-rangers.jpg", "filters": "tv", "label": "Power Rangers", "link": "" },
	{ "file": "song-of-ice-and-fire.jpg", "filters": "book tv", "label": "A Song of Ice and Fire / Game of Thrones", "link": "https://www.hbo.com/game-of-thrones" },
	{ "file": "star-wars-the-clone-wars.jpg", "filters": "tv", "label": "Star Wars: The Clone Wars", "link": "https://www.starwars.com/series/star-wars-the-clone-wars" },
	{ "file": "survivor.jpg", "filters": "tv", "label": "Survivor", "link": "https://www.cbs.com/shows/survivor/" },
	{ "file": "vikings.jpg", "filters": "tv history", "label": "Vikings", "link": "https://www.netflix.com/title/70301870" },
	{ "file": "walking-dead-comics.jpg", "filters": "tv comic", "label": "The Walking Dead", "link": "https://www.netflix.com/title/70177057" },
	{ "file": "witcher.jpg", "filters": "tv", "label": "The Witcher", "link": "https://www.netflix.com/title/80189685" },
	// { "file": "", "filters": "", "label": "", "link": "" },
]