filtersMedia = [
	{ "filter": "book", "text": "Books" },
	{ "filter": "comic", "text": "Comics" },
	{ "filter": "vg", "text": "Gaming" },
	{ "filter": "misc", "text": "Misc" },
	{ "filter": "movie", "text": "Movies" },
	{ "filter": "sport", "text": "Sports" },
	{ "filter": "tv", "text": "Tv" },
]

filtersFranchise = [
	{ "filter": "db", "text": "Dragon Ball" },
	{ "filter": "dc", "text": "DC" },
	{ "filter": "marvel", "text": "Marvel" },
	{ "filter": "mcu", "text": "MCU" },
	{ "filter": "pr", "text": "Power Rangers" },
	{ "filter": "sw", "text": "Star Wars" },
]

filtersOther = [
	{ "filter": "comedy", "text": "Comedy" },
	{ "filter": "history", "text": "History" },
	{ "filter": "politics", "text": "Politics" },
	{ "filter": "scifi", "text": "Sci-fi" },
]

posters = [
	// { "label": "100, The", "file": "100.png", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/The_100_(TV_series)" },
	// { "label": "Barbarians", "file": "barbarians.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Barbarians_(2020_TV_series)" },
	// { "label": "Casino [1995]", "file": "casino-film.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/Casino_(1995_film)" },
	// { "label": "Goodfellas [1990]", "file": "goodfellas.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/Goodfellas" },
	// { "label": "Man Like Mobeen [2017]", "file": "man-like-mobeen.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Man_Like_Mobeen" },
	{ "label": "12 Angry Men [1957]", "file": "12-angry-men.png", "filters": "movie", "link": "https://www.imdb.com/title/tt0050083/?ref_=wl_li_tt" },
	{ "label": "30 Rock", "file": "30-rock.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/30_Rock" },
	{ "label": "300 - Film Series", "file": "300.png", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/300_(film)" },
	{ "label": "Altered Carbon", "file": "altered-carbon.png", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Altered_Carbon_(TV_series)" },
	{ "label": "Amazing Spider-Man Series [1963]", "file": "amazing-spider-man.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/The_Amazing_Spider-Man" },
	{ "label": "Andromeda", "file": "andromeda.jpg", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Andromeda_(TV_series)" },
	{ "label": "Angel [1999]", "file": "angel-tv.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Angel_(1999_TV_series)" },
	{ "label": "Animal Farm", "file": "animal-farm.png", "filters": "book politics", "link": "https://en.wikipedia.org/wiki/Animal_Farm" },
	{ "label": "Ant-Man Film Series", "file": "antman-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Ant-Man_(film)" },
	{ "label": "Aquaman [2018]", "file": "aquaman-film.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Aquaman_(film)" },
	{ "label": "Arrested Development", "file": "arrested-development.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Arrested_Development" },
	{ "label": "Arrow", "file": "arrow.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Arrow_(TV_series)" },
	{ "label": "Assassin's Creed Series", "file": "assassins-creed.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Assassin's_Creed" },
	{ "label": "Autobiogaphy of Malcolm X, The", "file": "autobiogaphy-malcolm-x.png", "filters": "book history politics", "link": "https://en.wikipedia.org/wiki/The_Autobiography_of_Malcolm_X" },
	{ "label": "Avatar: The Last Airbender", "file": "avatar-the-last-airbender.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Avatar:_The_Last_Airbender" },
	{ "label": "Avengers Film Series", "file": "avengers-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Avengers:_Endgame" },
	{ "label": "Batman - Tim Burton / Joel Schumacher Film Series", "file": "batman-film-tbjs.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Batman_in_film#Tim_Burton_and_Joel_Schumacher_series_(1989%E2%80%931997)" },
	{ "label": "Batman v Superman: Dawn of Justice [2016]", "file": "batman-v-superman-film.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Batman_v_Superman:_Dawn_of_Justice" },
	{ "label": "Batman: Arkham Series", "file": "batman-arkham.png", "filters": "vg dc", "link": "https://en.wikipedia.org/wiki/Batman:_Arkham" },
	{ "label": "Battlestar Galactica [2004]", "file": "battlestar-galactica.png", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Battlestar_Galactica_(2004_TV_series)" },
	{ "label": "Black Lightning", "file": "black-lightning.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Black_Lightning" },
	{ "label": "Black Mirror", "file": "black-mirror.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Black_Mirror" },
	{ "label": "Black Panther Film Series", "file": "black-panther-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Black_Panther_(film)" },
	{ "label": "Black-ish [2014]", "file": "blackish.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Black-ish" },
	{ "label": "BlackAF [2020]", "file": "blackaf.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/BlackAF" },
	{ "label": "Boys, The - Comic Series [2006]", "file": "boys-comic.png", "filters": "comic", "link": "https://en.wikipedia.org/wiki/The_Boys_(comics)" },
	{ "label": "Boys, The - Tv Series [2019]", "file": "boys-tv.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Boys_(2019_TV_series)" },
	{ "label": "Breaking Bad", "file": "breaking-bad.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Breaking_Bad" },
	{ "label": "Brooklyn Nine-Nine", "file": "brooklyn-nine-nine.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Brooklyn_Nine-Nine" },
	{ "label": "Buffy the Vampire Slayer", "file": "buffy-the-vampire-slayer.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Buffy_the_Vampire_Slayer" },
	{ "label": "Captain America Film Series", "file": "captain-america-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Captain_America:_The_First_Avenger" },
	{ "label": "Captain Marvel Film Series", "file": "captain-marvel-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Captain_Marvel_(film)" },
	{ "label": "Chewing Gum [2015]", "file": "chewing-gum.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Chewing_Gum_(TV_series)" },
	{ "label": "Civil War Crossover Event", "file": "civil-war.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/Civil_War_(comics)" },
	{ "label": "Community", "file": "community.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Community_(TV_series)" },
	{ "label": "Cougar Town [2009]", "file": "cougar-town.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Cougar_Town" },
	{ "label": "Daredevil - Tv Series", "file": "daredevil-tv.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/Daredevil_(TV_series)" },
	{ "label": "Dark Knight, The - Film Trilogy", "file": "dark-knight-trilogy.png", "filters": "movie dc", "link": "https://en.wikipedia.org/wiki/Batman_in_film#Christopher_Nolan" },
	{ "label": "Darth Maul: Son of Dathomir Comic", "file": "darth-maul-sod.png", "filters": "comic sw", "link": "https://starwars.fandom.com/wiki/Star_Wars:_Darth_Maul%E2%80%94Son_of_Dathomir" },
	{ "label": "Deadpool - Comic Series [1997]", "file": "deadpool.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/Deadpool" },
	{ "label": "Deadpool - Film Series", "file": "deadpool-film.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/Deadpool_(film)" },
	{ "label": "Defenders, The - Tv Series", "file": "defenders-tv.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/The_Defenders_(miniseries)" },
	{ "label": "Dexter", "file": "dexter.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Dexter_(TV_series)" },
	{ "label": "Dirilis Ertugrul", "file": "dirilis-ertugrul.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Dirili%C5%9F:_Ertu%C4%9Frul" },
	{ "label": "Doctor Strange - Film Series", "file": "doctor-strange-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Doctor_Strange_(2016_film)" },
	{ "label": "Don't Trust the B in Apartment 23", "file": "dttbia23.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Don%27t_Trust_the_B----_in_Apartment_23" },
	{ "label": "Donkey Kong Country", "file": "donkey-kong-country.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Donkey_Kong_Country" },
	{ "label": "Dragon Ball GT", "file": "dragon-ball-gt.jpg", "filters": "tv db", "link": "https://en.wikipedia.org/wiki/Dragon_Ball_GT" },
	{ "label": "Dragon Ball Super", "file": "dragon-ball-super.jpg", "filters": "tv db", "link": "https://en.wikipedia.org/wiki/Dragon_Ball_Super" },
	{ "label": "Dragon Ball Z", "file": "dragon-ball-z.jpg", "filters": "tv db", "link": "https://en.wikipedia.org/wiki/Dragon_Ball_Z" },
	{ "label": "Dragon Ball Z: Budokai Tenkaichi Video Game Series", "file": "dragon-ball-z-budokai-tenkaichi.png", "filters": "vg db", "link": "https://en.wikipedia.org/wiki/Dragon_Ball_Z:_Budokai_Tenkaichi" },
	{ "label": "Dragon Ball", "file": "dragon-ball.png", "filters": "tv db", "link": "https://en.wikipedia.org/wiki/Dragon_Ball_(TV_series)" },
	{ "label": "Ender's Game", "file": "enders-game.jpg", "filters": "book scifi politics", "link": "https://en.wikipedia.org/wiki/Ender%27s_Game" },
	{ "label": "Entourage [2004]", "file": "entourage.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Entourage_(American_TV_series)" },
	{ "label": "Flash, The - Tv Series [2014]", "file": "flash.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/The_Flash_(2014_TV_series)" },
	{ "label": "Forrest Gump [1994]", "file": "forrest-gump.png", "filters": "movie", "link": "https://www.imdb.com/title/tt0109830/?ref_=wl_li_tt" },
	{ "label": "Fresh Prince of Bel-Air [1990]", "file": "fpoba.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Fresh_Prince_of_Bel-Air" },
	{ "label": "Friends [1994]", "file": "friends.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Friends" },
	{ "label": "Fringe", "file": "fringe.png", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Fringe_(TV_series)" },
	{ "label": "Full House [1987]", "file": "full-house.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Full_House" },
	{ "label": "Game of Thrones", "file": "game-of-thrones.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Game_of_Thrones" },
	{ "label": "Get Down, The", "file": "get-down.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Get_Down" },
	{ "label": "Gladiator [2000]", "file": "gladiator.png", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/Gladiator_(2000_film)" },
	{ "label": "Go Go Power Rangers Comic Series [2017]", "file": "go-go-power-ranger-comic.png", "filters": "comic pr", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "label": "Go On [2012]", "file": "go-on.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Go_On_(TV_series)" },
	{ "label": "Godfather, The - Film Trilogy", "file": "godfather.jpg", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_Godfather_(film_series)" },
	{ "label": "Good Place, The [2016]", "file": "good-place.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Good_Place" },
	{ "label": "Gotham [2014]", "file": "gotham.jpg", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Gotham_(TV_series)" },
	{ "label": "Grinder, The [2015]", "file": "grinder.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Grinder_(TV_series)" },
	{ "label": "Grown-ish [2019]", "file": "grownish.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Grown-ish" },
	{ "label": "Guardians of the Galaxy Film Series", "file": "gotg-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(film)" },
	{ "label": "Halo Series", "file": "halo.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Halo_(franchise)" },
	{ "label": "Halt and Catch Fire [2014]", "file": "halt-and-catch-fire.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Halt_and_Catch_Fire_(TV_series)" },
	{ "label": "Handmaid's Tale, The", "file": "handmaids-tale.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Handmaid%27s_Tale_(TV_series)" },
	{ "label": "Happy Endings [2011]", "file": "happy-endings.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Happy_Endings_(TV_series)" },
	{ "label": "Harry Potter - Book Series", "file": "harry-potter-books.png", "filters": "book", "link": "https://en.wikipedia.org/wiki/Harry_Potter" },
	{ "label": "Harry Potter - Film Series", "file": "harry-potter-films.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/Harry_Potter_(film_series)" },
	{ "label": "Heroes [2006]", "file": "heroes.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Heroes_(American_TV_series)" },
	{ "label": "House of Lies [2012]", "file": "house-of-lies.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/House_of_Lies" },
	{ "label": "House of M", "file": "house-of-m.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/House_of_M" },
	{ "label": "How I Met Your Mother [2005]", "file": "himym.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/How_I_Met_Your_Mother" },
	{ "label": "Inception [2010]", "file": "inception.png", "filters": "movie scifi", "link": "https://www.imdb.com/title/tt1375666/?ref_=wl_li_tt" },
	{ "label": "Incredbile Hulk, The [2008]", "file": "incredible-hulk-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/The_Incredible_Hulk_(film)" },
	{ "label": "Infinity Gauntlet Event", "file": "infinity-gauntlet.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/The_Infinity_Gauntlet" },
	{ "label": "Inglorious Basterds", "file": "inglorious-basterds.png", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/Inglourious_Basterds" },
	{ "label": "Iron Fist - Tv Series", "file": "iron-fist.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/Iron_Fist_(TV_series)" },
	{ "label": "Iron Man - Film Series", "file": "iron-man-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Iron_Man_(2008_film)" },
	{ "label": "Jessica Jones - Tv Series", "file": "jessica-jones.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/Jessica_Jones_(TV_series)" },
	{ "label": "Joker [2019]", "file": "joker-film.png", "filters": "movie dc", "link": "https://en.wikipedia.org/wiki/Joker_(2019_film)" },
	{ "label": "Justice League Film Series", "file": "justice-league-film.png", "filters": "movie dc", "link": "https://en.wikipedia.org/wiki/Justice_League_(film)" },
	{ "label": "Killer Instinct [1994]", "file": "killer-instinct.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Killer_Instinct_(1994_video_game)" },
	{ "label": "Kim's Convenience", "file": "kims-convenience.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Kim%27s_Convenience" },	
	{ "label": "King Arthur [2004]", "file": "king-arthur-film.png", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/King_Arthur_(2004_film)" },
	{ "label": "Kingdom of Heaven [2005]", "file": "kingdom-of-heaven.png", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/Kingdom_of_Heaven_(film)" },
	{ "label": "Kite Runner, The", "file": "kite-runner.png", "filters": "book politics", "link": "https://en.wikipedia.org/wiki/The_Kite_Runner" },
	{ "label": "Kurulus: Osman", "file": "kurulus-osman.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Kurulu%C5%9F:_Osman" },
	{ "label": "Last Kingdom, The", "file": "last-kingdom.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/The_Last_Kingdom_(TV_series)" },
	{ "label": "Legend of Korra, The", "file": "legend-of-korra.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Legend_of_Korra" },
	{ "label": "Legends of Tomorrow", "file": "legends-of-tomorrow.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Legends_of_Tomorrow" },
	{ "label": "Lego Batman Movie, The [2017]", "file": "lego-batman-movie.png", "filters": "movie dc", "link": "https://en.wikipedia.org/wiki/The_Lego_Batman_Movie" },
	{ "label": "Lion King Film Series", "file": "lion-king.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_Lion_King" },
	{ "label": "Locke & Key", "file": "locke-and-key.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Locke_%26_Key_(TV_series)" },
	{ "label": "Lord of the Rings Series", "file": "lord-of-the-rings.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)" },
	{ "label": "Lost", "file": "lost.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Lost_(TV_series)" },
	{ "label": "Love - Tv Series", "file": "love-netflix.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Love_(TV_series)" },
	{ "label": "Luke Cage - Tv Series", "file": "luke-cage.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/Luke_Cage_(TV_series)" },
	{ "label": "MMPR / Justic League Crossover Comic Event", "file": "mmpr-justice-league.png", "filters": "comic dc pr", "link": "https://en.wikipedia.org/wiki/Justice_League/Mighty_Morphin_Power_Rangers" },
	{ "label": "MMPR / Ninja Turtles Crossover Comic Event", "file": "mmpr-ninja-turtle.png", "filters": "comic pr", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "label": "Mad Men", "file": "mad-men.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Mad_Men" },
	{ "label": "Magic: The Gathering - Trading Card Game", "file": "magic-the-gathering.png", "filters": "misc", "link": "https://magic.wizards.com/en" },
	{ "label": "Man of Steel [2013]", "file": "man-of-steel-film.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Man_of_Steel_(film)" },
	{ "label": "Mandalorian, The", "file": "mandalorian.png", "filters": "tv sw", "link": "https://en.wikipedia.org/wiki/The_Mandalorian" },
	{ "label": "Marvel: Ultimate Alliance Series", "file": "marvel-ultimate-alliance.png", "filters": "vg marvel", "link": "https://en.wikipedia.org/wiki/Marvel%3A_Ultimate_Alliance" },
	{ "label": "Master of None", "file": "master-of-none.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Master_of_None" },
	{ "label": "Matrix, The - Film Series", "file": "matrix.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_Matrix_(franchise)" },
	{ "label": "Megaman Battle Network Series", "file": "megaman-battle-network.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Mega_Man_Battle_Network" },
	{ "label": "Message, The [1976]", "file": "message-movie.jpg", "filters": "movie history", "link": "https://en.wikipedia.org/wiki/The_Message_(1976_film)" },
	{ "label": "Messiah", "file": "messiah.jpg", "filters": "tv politics", "link": "https://en.wikipedia.org/wiki/Messiah_(American_TV_series)" },
	{ "label": "Middle, The", "file": "middle-the.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Middle_(TV_series)" },
	{ "label": "Mighty Avengers - Comic Series [2007]", "file": "mighty-avengers-comic.png", "filters": "comic marvel", "link": "https://marvel.fandom.com/wiki/Mighty_Avengers_(Initiative)_(Earth-616)" },
	{ "label": "Mighty Morphin Comic Series [2020]", "file": "mighty-morphin-comic.png", "filters": "comic pr", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "label": "Mighty Morphin Power Rangers - Comic Series [2016]", "file": "mmpr-boom-studios.png", "filters": "comic pr", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "label": "Mighty Morphin Power Rangers Series [1993]", "file": "mmpr.png", "filters": "tv pr", "link": "https://en.wikipedia.org/wiki/Mighty_Morphin_Power_Rangers" },
	{ "label": "Mindy Project, The", "file": "mindy-project.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Mindy_Project" },
	{ "label": "Modern Family", "file": "modern-family.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Modern_Family" },
	{ "label": "Mr. Robot", "file": "mr-robot.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Mr._Robot" },
	{ "label": "New Avengers Comic Series [2005]", "file": "new-avengers-comic.png", "filters": "comic marvel", "link": "https://marvel.fandom.com/wiki/New_Avengers_(Earth-616)" },
	{ "label": "New Girl", "file": "new-girl.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/New_Girl" },
	{ "label": "New Mutants, The [2020]", "file": "new-mutants-film.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/The_New_Mutants_(film)" },
	{ "label": "Nineteen Eighty-Four", "file": "nineteen-eighty-four.png", "filters": "book politics", "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four" },
	{ "label": "Office, The", "file": "office.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/The_Office_(American_TV_series)" },
	{ "label": "Old Man Logan", "file": "old-man-logan.png", "filters": "comic marvel", "link": "https://marvel.fandom.com/wiki/Old_Man_Logan_(Story_Arc)" },
	{ "label": "Originals, The [2013]", "file": "originals.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Originals_(TV_series)" },
	{ "label": "Orphan Black [2013]", "file": "orphan-black.png", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Orphan_Black" },
	{ "label": "Parks and Recreation", "file": "parks-and-recreation.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Parks_and_Recreation" },
	{ "label": "Patriot Act with Hasan Minhaj", "file": "patriot-act-with-hasan-minhaj.png", "filters": "tv politics", "link": "https://en.wikipedia.org/wiki/Patriot_Act_with_Hasan_Minhaj" },
	{ "label": "Pirates of the Caribbean Film Series", "file": "pirates-of-the-caribbean.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/Pirates_of_the_Caribbean_(film_series)" },
	{ "label": "Pokemon GO", "file": "pokemon-go.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Pok%C3%A9mon_Go" },
	{ "label": "Pokemon: Trading Card Game", "file": "pokemon-tcg.png", "filters": "misc", "link": "https://en.wikipedia.org/wiki/Pok%C3%A9mon_Trading_Card_Game" },
	{ "label": "Power Rangers Comic Series [2020]", "file": "power-rangers-comic.png", "filters": "comic pr", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "label": "Power Rangers Zeo", "file": "power-rangers-zeo.png", "filters": "tv pr", "link": "https://powerrangers.fandom.com/wiki/Power_Rangers_Zeo" },
	{ "label": "Power Rangers in Space", "file": "power-rangers-in-space.png", "filters": "tv pr", "link": "https://powerrangers.fandom.com/wiki/Power_Rangers_in_Space" },
	{ "label": "Prince of Persia Video Game Series", "file": "prince-of-persia.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Prince_of_Persia" },
	{ "label": "Prison Break", "file": "prison-break.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Prison_Break" },
	{ "label": "Punisher, The - Tv Series", "file": "punisher-tv.png", "filters": "tv marvel", "link": "https://en.wikipedia.org/wiki/The_Punisher_(TV_series)" },
	{ "label": "ReBoot", "file": "reboot.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/ReBoot" },
	{ "label": "Rick and Morty", "file": "rick-and-morty.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Rick_and_Morty" },
	{ "label": "Rogue One: A Star Wars Story", "file": "star-wars-rogue-one.png", "filters": "movie sw", "link": "https://en.wikipedia.org/wiki/Rogue_One" },
	{ "label": "Rome [2005]", "file": "rome-tv.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Rome_(TV_series)" },
	{ "label": "Santa Clarita Diet [2017]", "file": "santa-clarita-diet.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Santa_Clarita_Diet" },
	{ "label": "Sapiens: A Brief History of Humankind", "file": "sapiens-abhoh.png", "filters": "book history politics", "link": "https://www.ynharari.com/book/sapiens-2/" },
	{ "label": "Schitt's Creek [2015]", "file": "schitts-creek.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Schitt%27s_Creek" },
	{ "label": "Scrubs [2001]", "file": "scrubs.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Scrubs_(TV_series)" },
	{ "label": "Seinfeld [1989]", "file": "seinfeld.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Seinfeld" },
	{ "label": "Series of Unfortunate Events, A - Tv Series", "file": "asoue-netflix.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/A_Series_of_Unfortunate_Events_(TV_series)" },
	{ "label": "Shawshank Redemption, The [1994]", "file": "shawshank-redemption.png", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_Shawshank_Redemption" },
	{ "label": "Shazam! [2019]", "file": "shazam-film.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Shazam!_(film)" },
	{ "label": "Shutter Island [2010]", "file": "shutter-island.png", "filters": "movie", "link": "https://www.imdb.com/title/tt1130884/?ref_=wl_li_tt" },
	{ "label": "Silicon Valley", "file": "silicon-valley.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)" },
	{ "label": "Smallville", "file": "smallville.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Smallville" },
	{ "label": "Solo: A Star Wars Story", "file": "star-wars-solo.png", "filters": "movie sw", "link": "https://en.wikipedia.org/wiki/Solo:_A_Star_Wars_Story" },
	{ "label": "Song of Ice and Fire, A - Book Series", "file": "song-of-ice-and-fire.png", "filters": "book", "link": "https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire" },
	{ "label": "Spartacus", "file": "spartacus.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Spartacus_(TV_series)" },
	{ "label": "Spider-Man MCU Film Series", "file": "spider-man-film-mcu.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Spider-Man:_Homecoming" },
	{ "label": "Spider-Man Original Film Series", "file": "spider-man-film-original.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/Spider-Man_in_film#Sam_Raimi_films_(2002%E2%80%932007)" },
	{ "label": "Spider-Man: Into the Spider-Verse [2018]", "file": "spider-man-itsv.png", "filters": "movie marvel", "link": "https://www.imdb.com/title/tt4633694/?ref_=wl_li_tt" },
	{ "label": "Spy, The [2019]", "file": "spy-tv.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/The_Spy_(TV_series)" },
	{ "label": "Star Wars - Original Film Series", "file": "star-wars-original.png", "filters": "movie sw", "link": "https://en.wikipedia.org/wiki/Star_Wars_Trilogy" },
	{ "label": "Star Wars - Prequel Film Series", "file": "star-wars-prequels.png", "filters": "movie sw", "link": "https://en.wikipedia.org/wiki/Star_Wars_prequel_trilogy" },
	{ "label": "Star Wars - Sequel Film Series", "file": "star-wars-sequel.png", "filters": "movie sw", "link": "https://en.wikipedia.org/wiki/Star_Wars_sequel_trilogy" },
	{ "label": "Star Wars: The Clone Wars [2008]", "file": "star-wars-the-clone-wars.png", "filters": "tv sw", "link": "https://en.wikipedia.org/wiki/Star_Wars:_The_Clone_Wars_(2008_TV_series)" },	
	{ "label": "Suburgatory", "file": "suburgatory.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Suburgatory" },
	{ "label": "Suits", "file": "suits.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Suits_(American_TV_series)" },
	{ "label": "Super Dragon Ball Heroes", "file": "dragon-ball-heroes.png", "filters": "tv db", "link": "https://en.wikipedia.org/wiki/Super_Dragon_Ball_Heroes_(anime)" },
	{ "label": "Super Mario All-Stars", "file": "super-mario-all-stars.png", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Super_Mario_All-Stars" },
	{ "label": "Super Mario World", "file": "super-mario-world.jpg", "filters": "vg", "link": "https://en.wikipedia.org/wiki/Super_Mario_World" },
	{ "label": "Super Star Wars SNES Series", "file": "super-star-wars.jpg", "filters": "vg sw", "link": "https://en.wikipedia.org/wiki/Super_Star_Wars" },
	{ "label": "Supergirl Tv Series [2015]", "file": "supergirl-tv.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Supergirl_(TV_series)" },
	{ "label": "Supernatural", "file": "supernatural.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Supernatural_(American_TV_series)" },
	{ "label": "Superstore [2015]", "file": "superstore.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Superstore_(TV_series)" },
	{ "label": "Survivor", "file": "survivor.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Survivor_(American_TV_series)" },
	{ "label": "That 70's Show [1998]", "file": "that-70s-show.jpg", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/That_%2770s_Show" },
	{ "label": "Thor - Film Series", "file": "thor-film.png", "filters": "movie marvel mcu", "link": "https://en.wikipedia.org/wiki/Thor_(film)" },
	{ "label": "Thousand Splendid Suns, A", "file": "thousand-splendid-suns.png", "filters": "book politics", "link": "https://en.wikipedia.org/wiki/A_Thousand_Splendid_Suns" },
	{ "label": "Titans", "file": "titans.png", "filters": "tv dc", "link": "https://en.wikipedia.org/wiki/Titans_(2018_TV_series)" },
	{ "label": "To Kill a Mockingbird", "file": "to-kill-a-mockingbird.png", "filters": "book", "link": "https://en.wikipedia.org/wiki/To_Kill_a_Mockingbird" },
	{ "label": "Toronto Maple Leafs", "file": "maple-leafs.png", "filters": "sport", "link": "https://www.nhl.com/mapleleafs" },
	{ "label": "Toronto Raptors", "file": "raptors.png", "filters": "sport", "link": "https://www.nba.com/raptors/" },
	{ "label": "Trailer Park Boys [2001]", "file": "trailer-park-boys.png", "filters": "tv comedy", "link": "https://en.wikipedia.org/wiki/Trailer_Park_Boys" },
	{ "label": "Troy [2004]", "file": "troy-film.png", "filters": "movie history", "link": "https://www.imdb.com/title/tt0332452/" },
	{ "label": "True Blood [2008]", "file": "true-blood.jpg", "filters": "tv", "link": "https://en.wikipedia.org/wiki/True_Blood" },
	{ "label": "Uncanny X-Men [1963]", "file": "uncanny-xmen.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/Uncanny_X-Men" },
	{ "label": "Usual Suspects, The [1995]", "file": "usual-suspects.png", "filters": "movie", "link": "https://www.imdb.com/title/tt0114814/?ref_=wl_li_tt" },
	{ "label": "Venom [2018]", "file": "venom-film.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/Venom_(2018_film)" },
	{ "label": "Venom: Lethal Protector [1993]", "file": "venom-lethal-protector.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/Venom:_Lethal_Protector" },
	{ "label": "Vikings", "file": "vikings.png", "filters": "tv history", "link": "https://en.wikipedia.org/wiki/Vikings_(2013_TV_series)" },
	{ "label": "Walking Dead, The - Comic Series [2003]", "file": "walking-dead-comic.png", "filters": "comic", "link": "https://en.wikipedia.org/wiki/The_Walking_Dead_(comic_book)" },
	{ "label": "Walking Dead, The", "file": "walking-dead-tv.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/Walking_Dead_(TV_series)" },
	{ "label": "WandaVision", "file": "wandavision.jpg", "filters": "tv marvel mcu", "link": "https://en.wikipedia.org/wiki/WandaVision" },
	{ "label": "Westworld [2016]", "file": "westworld.jpg", "filters": "tv scifi", "link": "https://en.wikipedia.org/wiki/Westworld_(TV_series)" },
	{ "label": "White Tiger, The", "file": "white-tiger.jpg", "filters": "movie", "link": "https://en.wikipedia.org/wiki/The_White_Tiger_(film)" },
	{ "label": "Who Is America?", "file": "who-is-america.png", "filters": "tv politics", "link": "https://en.wikipedia.org/wiki/Who_Is_America%3F" },
	{ "label": "Witcher, The", "file": "witcher.png", "filters": "tv", "link": "https://en.wikipedia.org/wiki/The_Witcher_(TV_series)" },
	{ "label": "Wonder Woman - Film Series", "file": "wonder-woman-film.png", "filters": "dc movie", "link": "https://en.wikipedia.org/wiki/Wonder_Woman_(2017_film)" },
	{ "label": "World War Hulk Event", "file": "world-war-hulk.png", "filters": "comic marvel", "link": "https://en.wikipedia.org/wiki/World_War_Hulk" },
	{ "label": "X-Men Legends - Video Game Series", "file": "x-men-legends.png", "filters": "vg marvel", "link": "https://en.wikipedia.org/wiki/X-Men_Legends" },
	{ "label": "X-Men Original Film Series", "file": "x-men-film-original.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/X-Men_(film_series)" },
	{ "label": "X-Men Past Film Series", "file": "x-men-film-past.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/X-Men_(film_series)" },
	{ "label": "X-Men Wolverine Film Series", "file": "wolverine-film.png", "filters": "movie marvel", "link": "https://en.wikipedia.org/wiki/X-Men_(film_series)" },
	{ "label": "Zombieland Film Series", "file": "zombieland.jpg", "filters": "movie", "link": "https://en.wikipedia.org/wiki/Zombieland_(franchise)" },
	// { "label": "", "file": "
	// ", "filters": "", "link": "" },
]