filters = [
	{ "filter": "book", "text": "Books" },
	{ "filter": "comic", "text": "Comics" },
	{ "filter": "vg", "text": "Gaming" },
	{ "filter": "misc", "text": "Misc" },
	{ "filter": "movie", "text": "Movies" },
	{ "filter": "tv", "text": "Tv" },
	{ "filter": "web", "text": "Web" },
]

subFilters = [
	{ "filter": "dc", "text": "DC" },
	{ "filter": "history", "text": "History" },
	{ "filter": "marvel", "text": "Marvel" },
	{ "filter": "netflix", "text": "Netflix" },
]

posters = [
	{ "file": "altered-carbon.jpg", "filters": "tv netflix", "label": "Altered Carbon", "link": "https://en.wikipedia.org/wiki/Altered_Carbon_(TV_series)" },
	{ "file": "amazing-spider-man.jpg", "filters": "comic marvel", "label": "The Amazing Spider Man Comic Series", "link": "https://en.wikipedia.org/wiki/The_Amazing_Spider-Man" },
	{ "file": "andromeda.jpg", "filters": "tv", "label": "Andromeda", "link": "https://en.wikipedia.org/wiki/Andromeda_(TV_series)" },
	{ "file": "animal-farm.jpg", "filters": "book", "label": "Animal Farm", "link": "https://en.wikipedia.org/wiki/Animal_Farm" },
	{ "file": "arrested-development.jpg", "filters": "tv netflix", "label": "Arrested Development", "link": "https://en.wikipedia.org/wiki/Arrested_Development" },
	{ "file": "assassins-creed.jpg", "filters": "vg", "label": "Assassin's Creed Series", "link": "https://en.wikipedia.org/wiki/Assassin's_Creed" },
	{ "file": "autobiogaphy-malcolm-x.jpg", "filters": "book history", "label": "The Autobiogaphy of Malcolm X", "link": "https://en.wikipedia.org/wiki/The_Autobiography_of_Malcolm_X" },
	{ "file": "avatar-the-last-airbender.jpg", "filters": "tv", "label": "Avatar: The Last Airbender", "link": "https://en.wikipedia.org/wiki/Avatar:_The_Last_Airbender" },
	{ "file": "batman-arkham.jpg", "filters": "vg dc", "label": "Batman: Arkham Series", "link": "https://en.wikipedia.org/wiki/Batman:_Arkham" },
	{ "file": "battlestar-galactica.jpg", "filters": "tv", "label": "Battlestar Galactica 2004 Series", "link": "https://en.wikipedia.org/wiki/Battlestar_Galactica_(2004_TV_series)" },
	{ "file": "black-mirror.jpg", "filters": "tv netflix", "label": "Black Mirror", "link": "https://en.wikipedia.org/wiki/Black_Mirror" },
	{ "file": "boys.jpg", "filters": "tv", "label": "The Boys", "link": "https://en.wikipedia.org/wiki/The_Boys_(2019_TV_series)" },
	{ "file": "brooklyn-nine-nine.jpg", "filters": "tv", "label": "Brooklyn Nine-Nine", "link": "https://en.wikipedia.org/wiki/Brooklyn_Nine-Nine" },
	{ "file": "civil-war.jpg", "filters": "comic marvel", "label": "Civil War Comic Crossover Event", "link": "https://en.wikipedia.org/wiki/Civil_War_(comics)" },
	{ "file": "community.jpg", "filters": "tv", "label": "Community", "link": "https://en.wikipedia.org/wiki/Community_(TV_series)" },
	{ "file": "dark-knight-trilogy.jpg", "filters": "movie dc", "label": "The Dark Knight Trilogy", "link": "https://en.wikipedia.org/wiki/Batman_in_film#Christopher_Nolan" },
	{ "file": "dc-arrowverse.jpg", "filters": "tv dc", "label": "DC's Arrowverse", "link": "https://en.wikipedia.org/wiki/Arrowverse" },
	{ "file": "dc-extended-universe.jpg", "filters": "movie dc", "label": "DC Extended Universe", "link": "https://en.wikipedia.org/wiki/DCEU" },
	{ "file": "deadpool.jpg", "filters": "comic marvel", "label": "Deadpool Comic Series", "link": "https://en.wikipedia.org/wiki/Deadpool" },
	{ "file": "dirilis-ertugrul.jpg", "filters": "tv history", "label": "Dirilis Ertugrul", "link": "https://en.wikipedia.org/wiki/Dirili%C5%9F:_Ertu%C4%9Frul" },
	{ "file": "donkey-kong-country.jpg", "filters": "vg", "label": "Donkey Kong Country", "link": "https://en.wikipedia.org/wiki/Donkey_Kong_Country" },
	{ "file": "dragon-ball.jpg", "filters": "tv", "label": "Dragon Ball Series", "link": "https://en.wikipedia.org/wiki/Dragon_Ball" },
	{ "file": "game-of-thrones.jpg", "filters": "tv", "label": "Game of Thrones", "link": "https://en.wikipedia.org/wiki/Game_of_Thrones" },
	{ "file": "godfather.jpg", "filters": "movie", "label": "The Godfather Trilogy", "link": "https://en.wikipedia.org/wiki/The_Godfather_(film_series)" },
	{ "file": "halo.jpg", "filters": "vg", "label": "Halo Series", "link": "https://en.wikipedia.org/wiki/Halo_(franchise)" },
	{ "file": "handmaids-tale.jpg", "filters": "tv", "label": "The Handmaid's Tale", "link": "https://en.wikipedia.org/wiki/The_Handmaid%27s_Tale_(TV_series)" },
	{ "file": "inglorious-basterds.jpg", "filters": "movie history", "label": "Inglorious Basterds", "link": "https://en.wikipedia.org/wiki/Inglourious_Basterds" },
	{ "file": "killer-instinct.jpg", "filters": "vg", "label": "Killer Instinct", "link": "https://en.wikipedia.org/wiki/Killer_Instinct_(1994_video_game)" },
	{ "file": "kims-convenience.jpg", "filters": "tv", "label": "Kim's Convenience", "link": "https://en.wikipedia.org/wiki/Kim%27s_Convenience" },
	{ "file": "kite-runner.jpg", "filters": "book", "label": "The Kite Runner", "link": "https://en.wikipedia.org/wiki/The_Kite_Runner" },
	{ "file": "last-kingdom.jpg", "filters": "tv history netflix", "label": "The Last Kingdom", "link": "https://en.wikipedia.org/wiki/The_Last_Kingdom_(TV_series)" },
	{ "file": "lion-king.jpg", "filters": "movie", "label": "The Lion King", "link": "https://en.wikipedia.org/wiki/The_Lion_King" },
	{ "file": "locke-and-key.jpg", "filters": "tv netflix", "label": "Locke & Key", "link": "https://en.wikipedia.org/wiki/Locke_%26_Key_(TV_series)" },
	{ "file": "lord-of-the-rings.jpg", "filters": "movie", "label": "Lord of the Rings Series", "link": "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings_(film_series)" },
	{ "file": "lost.jpg", "filters": "tv", "label": "Lost", "link": "https://en.wikipedia.org/wiki/Lost_(TV_series)" },
	{ "file": "mandalorian.jpg", "filters": "tv", "label": "The Mandalorian", "link": "https://en.wikipedia.org/wiki/The_Mandalorian" },
	{ "file": "maple-leafs.jpg", "filters": "misc", "label": "Toronto Maple Leafs", "link": "https://www.nhl.com/mapleleafs" },
	{ "file": "marvel-cinematic-universe.jpg", "filters": "movie marvel", "label": "Marvel Cinematic Universe", "link": "https://en.wikipedia.org/wiki/Marvel_Cinematic_Universe" },
	{ "file": "master-of-none.jpg", "filters": "tv netflix", "label": "Master of None", "link": "https://en.wikipedia.org/wiki/Master_of_None" },
	{ "file": "matrix.jpg", "filters": "movie", "label": "The Matrix Series", "link": "https://en.wikipedia.org/wiki/The_Matrix_(franchise)" },
	{ "file": "megaman-battle-network.jpg", "filters": "vg", "label": "Megaman Battle Network Series", "link": "https://en.wikipedia.org/wiki/Mega_Man_Battle_Network" },
	{ "file": "messiah.jpg", "filters": "tv", "label": "Messiah", "link": "https://en.wikipedia.org/wiki/Messiah_(American_TV_series)" },
	{ "file": "mmpr-boom-studios.jpg", "filters": "comic", "label": "MMPR Boom! Studios Series", "link": "https://en.wikipedia.org/wiki/Power_Rangers_(Boom!_Studios)" },
	{ "file": "mmpr-justice-league.jpg", "filters": "comic dc", "label": "MMPR / Justic League Crossover Comic Event", "link": "https://en.wikipedia.org/wiki/Justice_League/Mighty_Morphin_Power_Rangers" },
	{ "file": "mr-robot.jpg", "filters": "tv", "label": "Mr. Robot", "link": "https://en.wikipedia.org/wiki/Mr._Robot" },
	{ "file": "nineteen-eighty-four.jpg", "filters": "book", "label": "Nineteen Eighty-Four", "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four" },
	{ "file": "patriot-act-with-hasan-minhaj.jpg", "filters": "tv netflix", "label": "Patriot Act with Hasan Minhaj", "link": "https://en.wikipedia.org/wiki/Patriot_Act_with_Hasan_Minhaj" },
	{ "file": "pirates-of-the-caribbean.jpg", "filters": "movie", "label": "Pirates of the Caribbean Series", "link": "https://en.wikipedia.org/wiki/Pirates_of_the_Caribbean_(film_series)" },
	{ "file": "pokemon-go.jpg", "filters": "vg", "label": "Pokemon GO", "link": "https://en.wikipedia.org/wiki/Pok%C3%A9mon_Go" },
	{ "file": "power-rangers.jpg", "filters": "tv", "label": "Power Rangers", "link": "https://en.wikipedia.org/wiki/Power_Rangers" },
	{ "file": "prince-of-persia.jpg", "filters": "vg", "label": "Price of Persia Series", "link": "https://en.wikipedia.org/wiki/Prince_of_Persia" },
	{ "file": "priosn-break.jpg", "filters": "tv", "label": "Prison Break", "link": "https://en.wikipedia.org/wiki/Prison_Break" },
	{ "file": "raptors.jpg", "filters": "misc", "label": "Toronto Raptors", "link": "https://www.nba.com/raptors/" },
	{ "file": "rick-and-morty.jpg", "filters": "tv", "label": "Rick and Morty", "link": "https://en.wikipedia.org/wiki/Rick_and_Morty" },
	{ "file": "silicon-valley.jpg", "filters": "tv", "label": "Silicon Valley", "link": "https://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)" },
	{ "file": "smallville.jpg", "filters": "tv dc", "label": "Smallville", "link": "https://en.wikipedia.org/wiki/Smallville" },
	{ "file": "song-of-ice-and-fire.jpg", "filters": "book", "label": "A Song of Ice and Fire Series", "link": "https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire" },
	{ "file": "spartacus.jpg", "filters": "tv history", "label": "Spartacus", "link": "https://en.wikipedia.org/wiki/Spartacus_(TV_series)" },
	{ "file": "star-wars-the-clone-wars.jpg", "filters": "tv", "label": "Star Wars: The Clone Wars", "link": "https://en.wikipedia.org/wiki/Star_Wars:_The_Clone_Wars_(2008_TV_series)" },
	{ "file": "star-wars.jpg", "filters": "movie", "label": "Star Wars", "link": "https://en.wikipedia.org/wiki/Star_Wars" },
	{ "file": "suits.jpg", "filters": "tv", "label": "Suits", "link": "https://en.wikipedia.org/wiki/Suits_(American_TV_series)" },
	{ "file": "super-mario-all-stars.jpg", "filters": "vg", "label": "Super Mario All-Stars", "link": "https://en.wikipedia.org/wiki/Super_Mario_All-Stars" },
	{ "file": "survivor.jpg", "filters": "tv", "label": "Survivor", "link": "https://en.wikipedia.org/wiki/Survivor_(American_TV_series)" },
	{ "file": "thousand-splendid-suns.jpg", "filters": "book", "label": "A Thousand Splendid Suns", "link": "https://en.wikipedia.org/wiki/A_Thousand_Splendid_Suns" },
	{ "file": "titans.jpg", "filters": "tv dc", "label": "Titans", "link": "https://en.wikipedia.org/wiki/Titans_(2018_TV_series)" },
	{ "file": "uncanny-xmen.jpg", "filters": "comic marvel", "label": "Uncanny X-Men Comic Series", "link": "https://en.wikipedia.org/wiki/Uncanny_X-Men" },
	{ "file": "vikings.jpg", "filters": "tv history", "label": "Vikings", "link": "https://en.wikipedia.org/wiki/Vikings_(2013_TV_series)" },
	{ "file": "walking-dead-comic.jpg", "filters": "comic", "label": "The Walking Dead Comic Series", "link": "https://en.wikipedia.org/wiki/The_Walking_Dead_(comic_book)" },
	{ "file": "walking-dead-tv.jpg", "filters": "tv", "label": "The Walking Dead", "link": "https://en.wikipedia.org/wiki/Walking_Dead_(TV_series)" },
	{ "file": "witcher.jpg", "filters": "tv netflix", "label": "The Witcher", "link": "https://en.wikipedia.org/wiki/The_Witcher_(TV_series)" },
	{ "file": "world-war-hulk.jpg", "filters": "comic marvel", "label": "World War Hulk Comic Event", "link": "https://en.wikipedia.org/wiki/World_War_Hulk" },
	// { "file": "", "filters": "", "label": "", "link": "" },
]